apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-gr
  labels:
    app: weather-gr
spec:
  replicas: 3     # three pod
  selector:
    matchLabels:
      app: weather-gr
  template:
    metadata:
      labels:
        app: weather-gr
    spec:
      containers:
      - name: weather-gr
        image: leegyurye/weather-grapi
        ports:
        - containerPort: 8000 # Container Port(pod  container port (pod port) 
