apiVersion: v1
kind: Service
metadata:
  name: weather-gr
  labels:
    run: weather-gr
spec:
  type: NodePort #service type
  ports:
  - nodePort: 31200 #outter port
    port: 8080 #service port
    targetPort: 8000 #container port(pod port)
    protocol: TCP
  selector:
    app: weather-gr
  type: LoadBalancer
  externalIPs: 
  - 52.78.157.81
