--------------------------------------------------------
--  파일이 생성됨 - 화요일-3월-28-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BUYTBL
--------------------------------------------------------

  CREATE TABLE "HR"."BUYTBL" 
   (	"IDNUM" NUMBER(8,0), 
	"USERID" CHAR(8 BYTE), 
	"PRODNAME" NCHAR(6), 
	"GROUPNAME" NCHAR(4), 
	"PRICE" NUMBER(8,0), 
	"AMOUNT" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.BUYTBL
SET DEFINE OFF;
Insert into HR.BUYTBL (IDNUM,USERID,PRODNAME,GROUPNAME,PRICE,AMOUNT) values (21,'KBS     ','운동화   ',null,30,2);
Insert into HR.BUYTBL (IDNUM,USERID,PRODNAME,GROUPNAME,PRICE,AMOUNT) values (22,'KBS     ','노트북   ','전자  ',1000,1);
Insert into HR.BUYTBL (IDNUM,USERID,PRODNAME,GROUPNAME,PRICE,AMOUNT) values (23,'JYP     ','모니터   ','전자  ',200,1);
Insert into HR.BUYTBL (IDNUM,USERID,PRODNAME,GROUPNAME,PRICE,AMOUNT) values (24,'BBK     ','모니터   ','전자  ',200,5);
Insert into HR.BUYTBL (IDNUM,USERID,PRODNAME,GROUPNAME,PRICE,AMOUNT) values (25,'KBS     ','청바지   ','의류  ',50,3);
Insert into HR.BUYTBL (IDNUM,USERID,PRODNAME,GROUPNAME,PRICE,AMOUNT) values (26,'BBK     ','메모리   ','전자  ',80,10);
Insert into HR.BUYTBL (IDNUM,USERID,PRODNAME,GROUPNAME,PRICE,AMOUNT) values (27,'SSK     ','책     ','서적  ',15,5);
Insert into HR.BUYTBL (IDNUM,USERID,PRODNAME,GROUPNAME,PRICE,AMOUNT) values (28,'EJW     ','책     ','서적  ',15,2);
Insert into HR.BUYTBL (IDNUM,USERID,PRODNAME,GROUPNAME,PRICE,AMOUNT) values (29,'EJW     ','청바지   ','의류  ',50,1);
Insert into HR.BUYTBL (IDNUM,USERID,PRODNAME,GROUPNAME,PRICE,AMOUNT) values (30,'BBK     ','운동화   ',null,30,2);
Insert into HR.BUYTBL (IDNUM,USERID,PRODNAME,GROUPNAME,PRICE,AMOUNT) values (31,'EJW     ','책     ','서적  ',15,1);
Insert into HR.BUYTBL (IDNUM,USERID,PRODNAME,GROUPNAME,PRICE,AMOUNT) values (32,'BBK     ','운동화   ',null,30,2);
--------------------------------------------------------
--  DDL for Index SYS_C007036
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007036" ON "HR"."BUYTBL" ("IDNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BUYTBL
--------------------------------------------------------

  ALTER TABLE "HR"."BUYTBL" ADD PRIMARY KEY ("IDNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."BUYTBL" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "HR"."BUYTBL" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "HR"."BUYTBL" MODIFY ("PRODNAME" NOT NULL ENABLE);
  ALTER TABLE "HR"."BUYTBL" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "HR"."BUYTBL" MODIFY ("IDNUM" NOT NULL ENABLE);
